server:
  port: 9092
  servlet:
    context-path: /

spring:
#  profiles:
#    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true
    username: root
    password: 19910626zjl
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect

# 监控相关
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
  server:
    port: 9099
